name: atr-discovery-studio
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit=1.41.1
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.5.2
  - plotly=5.24.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - rdkit=2024.03.5
  - xgboost=2.1.1
  - joblib=1.4.2
  - pillow=10.4.0
